In [3]:
import numpy as np
import numpy.random as npr
import matplotlib.pyplot as plt 
%matplotlib inline

In [4]:
npr.rand(10)

array([ 0.15770553,  0.85954825,  0.08021388,  0.33170043,  0.71654367,
        0.97634286,  0.13581568,  0.26023086,  0.23180526,  0.27368897])

In [5]:
npr.rand(5,5)

array([[ 0.70726993,  0.35644923,  0.47638866,  0.2125853 ,  0.37149132],
       [ 0.69118625,  0.80509633,  0.38131105,  0.31254053,  0.06420925],
       [ 0.18146393,  0.64301815,  0.34088042,  0.16795204,  0.14775843],
       [ 0.11749367,  0.6754518 ,  0.93549037,  0.39837835,  0.74746645],
       [ 0.8821569 ,  0.58810982,  0.90335689,  0.40750399,  0.43660684]])

In [8]:
a = 5
b = 10
npr.rand(10)*(b-a)+a

array([ 7.1421368 ,  9.60238112,  7.8141938 ,  7.08609663,  9.68184402,
        6.72886284,  6.81152229,  8.47147909,  5.18107609,  6.63094332])